import MainTheoremSpectral
#check WithLp.linearEquiv
#check WithLp.linearEquiv_apply
#check WithLp.linearEquiv_symm_apply
#check LinearEquiv.finrank_eq
#check Matrix.toLpLin
#check Matrix.toLpLin_apply
#check Matrix.toEuclideanLin
#check Matrix.isSymmetric_toEuclideanLin_iff
#check LinearMap.eigenspace
#check LinearEquiv.ofEq
#check LinearEquiv.equivSubmodule
#check LinearEquiv.submoduleMap
#check Submodule.equivSubtype
#check LinearEquiv.ofBijective
#check LinearEquiv.restrict
#check LinearMap.ker_eq_comap
#check LinearMap.ker_eq_bot
#check LinearEquiv.map_subtype
#check Matrix.IsHermitian.card_filter_eigenvalues_eq
#check Matrix.IsHermitian.eigenvectorBasis
#check Matrix.IsHermitian.eigenvalues
#check Matrix.IsHermitian.eigenspace
#check Matrix.IsHermitian.eigenvalue_mem
#check LinearMap.IsSymmetric.card_filter_eigenvalues_eq
#check LinearMap.IsSymmetric.trace_eq_sum_eigenvalues
#check LinearMap.IsSymmetric.eigenvalues
#check LinearMap.IsSymmetric.eigenvectorBasis
#check LinearMap.IsSymmetric.mulVec_eigenvectorBasis
#check LinearMap.trace_eq_sum_eigenvalues
#check LinearMap.trace_eq_sum_inner
#check Module.End.mul_apply
#check Module.End.one_apply
#check LinearMap.mul_apply'
#check LinearMap.comp_apply
#check LinearMap.IsSymmetric.apply_eigenvectorBasis
#check LinearMap.IsSymmetric.hasEigenvalue_eigenvalues
#check LinearMap.IsSymmetric.has_eigenvalue_eigenvalues
#check LinearMap.IsSymmetric.eigenvalues_mem
#check Module.End.HasEigenvalue
#check Module.End.hasEigenvalue_iff
#check Module.End.hasEigenvalue_iff_exists
#check Module.End.HasEigenvector
#check Module.End.hasEigenvector_iff
#check Module.End.eigenspace
#check Module.End.eigenspace_eq_ker
#check Module.End.mem_eigenspace_iff
#check Module.End.mem_eigenspace
#check Module.End.eigenspace
#check Module.End.eigenspace_eq_ker
#check LinearMap.congr_fun
#check LinearEquiv.toLinearMap
#check LinearMap.mul
#check LinearMap.comp_apply
#check Submodule.mem_map
#check Submodule.mem_map_of_mem
#check Submodule.map_le_iff_le_comap
#check Submodule.map_le_iff_le_comap
#check LinearEquiv.submoduleMap
#check LinearEquiv.map_apply
