import Mathlib
#check Real.sqrt_mul
#check Real.sqrt_mul'
#check Real.sq_sqrt
#check Real.sqrt_sq_eq_abs
#check Real.sqrt_pos.2
#check Real.self_le_sinh_iff
#check Real.sinh_eq
#check Real.exp_add
#check Real.exp_sub
#check Real.exp_neg
#check Real.exp_log
#check Real.log_div
#check abs_mul
#check abs_of_nonneg
#check abs_of_nonpos
#check sq_le_sq₀
#check sq_le_sq
#check mul_self_le_mul_self
#check sq_le_sq₀
