import MainTheoremSpectral
import MainTheoremArithmetic
#check Module.finrank_pos
#check Module.finrank_pos_iff
#check Submodule.finrank_pos
#check Submodule.finrank_pos_iff
#check Module.finrank_pos_iff
#check Submodule.ne_bot_iff
#check Submodule.mem_ker
#check LinearMap.mem_ker
#check div_mul_cancel₀
#check div_mul_cancel₀
