import MainTheoremSpectral
#check SimpleGraph.Iso
#check SimpleGraph.Iso.trans
#check SimpleGraph.Iso.symm
#check RelIso.trans
#check RelIso.symm
#check SimpleGraph.Iso.map_adj
#check RelIso.map_rel_iff
#check SimpleGraph.isoToRelIso
#check Equiv.Perm
#check Fintype.card_congr
#check Fintype.card_subtype_iff
#check Set.ncard
#check Finset.card_biUnion
#check Equiv.trans_apply
#check Equiv.trans
#check Equiv.coe_trans
#check Real.one_le_sqrt
#check Real.sqrt_le
#check Real.sqrt_le_sqrt
