import CheckLemma22
#check Orthonormal.inner_self
#check Orthonormal.norm
#check Orthonormal.norm_eq_one
#check OrthonormalBasis.toBasis
#check Finset.card_insert_le
#check SimpleGraph.loopless
#check SimpleGraph.symm
#check Std.Irrefl
#check Std.Symm
#print Std.Irrefl
#print Std.Symm
#check Real.sqrt_pos.2
#check Real.sq_sqrt
#check Real.sqrt_sq_eq_abs
#check Real.log_mul
#check Real.log_sq
#check Real.log_rpow
#check Real.log_div
#check Real.log_le_sub_one_of_pos
#check sq_le_sq₀
#check sq_le_sq₀
#check sq_le_sq
#check mul_self_le_mul_self
#check mul_self_le_mul_self_iff
#check sq_le_sq₀
#check Real.log_nonneg
#check PiLp.norm_sq_eq_sum_norm_sq
#check PiLp.norm_sq_eq_sum
#check EuclideanSpace.norm_sq_eq_sum
#check norm_sq_eq_sum_norm_sq
#check norm_sq_eq_sum
#check Real.sinh_eq
#check Real.sinh_eq_exp_sub_exp
#check Real.self_le_sinh_iff
#check Real.exp_log
#check Real.log_div
